[package]
name = "rkit"
version = "1.7.0"
edition = "2024"

[lib]
path = "src/lib.rs"

[[bin]]
name = "tree"
path = "src/bin/tree.rs"

[[bin]]
name = "dos2unix"
path = "src/bin/dos2unix.rs"

[[bin]]
name = "brew-update"
path = "src/bin/brew-update.rs"

[[bin]]
name = "repoctl"
path = "src/bin/repoctl.rs"
